### ISSUE TITLE
Libvlc internal player

### ISSUE THREAD

**Issue by julienacquaviva** [Stremio/vlc-android-sdk#2]
Hi, is this a way to integrate vlc player into Stremio and replace actual internal player ? Thanks

**Comment by Ivshti** [comment]
Stremio already uses VLC underneath. The reason it's less performant is that it's (1) an older version and (2) integrated within the React Native UI

We're working on updating it/making improvements to it

**Comment by julienacquaviva** [comment]
Thank you very much for your answers. Hope it will work better with the
Nvidia Shield and if you add an audio delay setting, would be perfection.

Le sam. 30 mai 2020 à 14:17, Ivo Georgiev <notifications@github.com> a
écrit :
